name: Backend

on: [push]

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: | 
          uv python install python${{ matrix.python-version }}
          uv sync --group linting

      - name: Run linter
        run: uv run ruff check --output-format=grouped >> $GITHUB_STEP_SUMMARY

  tests:
    name: Tests
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: | 
          uv python install python${{ matrix.python-version }}
          uv sync --group testing

      - name: Run tests
        run: uv run pytest --cov --cov-report=
        env:
          pytest_github_report: true
          pytest_report_title: ""

      - name: Save coverage database
        uses: actions/upload-artifact@v4
        with:
          name: .coverage-${{ matrix.python-version }}
          path: .coverage
          overwrite: true
          include-hidden-files: true

  coverage:
    name: Coverage
    if: ${{ success() || failure() }}
    needs: [tests]
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: |
          uv python install python${{ matrix.python-version }}
          uv sync --group testing

      - name: Load coverage database
        uses: actions/download-artifact@v4
        with:
          name: .coverage-${{ matrix.python-version }}

      - name: Run coverage report
        run: uv run coverage report --format=markdown >> $GITHUB_STEP_SUMMARY
